apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jokemeter-svc-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: jokemeter
  jobLabel: jokemeter
  endpoints:
  - path: /metrics
    port: jokemeter
    scheme: http
    interval: 5s
